- hosts: clickhouse
  gather_facts: yes
  become: yes
  roles: 
      - role: clickhouse
  vars:
    clickhouse_users_custom:
    - { name: "testuser",
        password_sha256_hex: "f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2",
        networks: "{{ clickhouse_networks_default }}",
        profile: "default",
        quota: "default",
        dbs: [ testu1 ] ,
        comment: "classic user with plain password"}
    - { name: "testuser2",
        password: "testplpassword",
        networks: "{{ clickhouse_networks_default }}",
        profile: "default",
        quota: "default",
        dbs: [ testu2 ] ,
        comment: "classic user with hex password"}
    - { name: "testuser3",
        password: "testplpassword",
        networks: { 192.168.0.0/16, 127.0.0.1 },
        profile: "default",
        quota: "default",
        dbs: [ default,system,testu1,testu2,testu3 ] ,
        comment: "classic user with multi dbs and multi-custom network allow password"}
    clickhouse_dicts:
      test1:
        name: test_dict
        odbc_source:
          connection_string: "DSN=testdb"
          source_table: "dict_source"
        lifetime:
          min: 300
          max: 360
        layout: hashed
        structure:
          key: "testIntKey"
          attributes:
          - { name: testAttrName, type: UInt32, null_value: 0 }
      test2:
        name: test_dict
        odbc_source:
          connection_string: "DSN=testdb"
          source_table: "dict_source"
        lifetime:
          min: 300
          max: 360
        layout: complex_key_hashed
        structure:
          key:
            attributes:
            - { name: testAttrComplexName, type: String }
          attributes:
          - { name: testAttrName, type: String, null_value: "" }
    clickhouse_dbs_custom:
    - { name: testu1 }
    - { name: testu2, state: present }
    - { name: testu3, state: absent }
    clickhouse_shards:
      your_shard_name:
      - { host: "maap-mongo-dev-01", port: 9000 }
      - { host: "maap-mongo-dev-04", port: 9000 }
      - { host: "maap-mongo-dev-05", port: 9000 }
      - { host: "maap-mongo-dev-06", port: 9000 }
    clickhouse_zookeeper_nodes:
    - { host: "10.244.5.24", port: 2181 }
    - { host: "10.244.3.77", port: 2181 }
    - { host: "10.244.5.23", port: 2181 }